### ISSUE TITLE
[提问]如何使用控制台交互？

### ISSUE THREAD

**Issue by Agnes4m** [nonebot/adapter-console#22]
通过[教程](https://nonebot.dev/docs/quick-start#%E5%B0%9D%E8%AF%95%E4%BD%BF%E7%94%A8)，并且确保安装了`Console `和`fastapi`,我在linux和win系统中，对于`nb run`启动的窗口都是无法交互的。

我在nb教程中并不能找到有关console相关使用方法，同时本项目readme是空的，我无从得知是否如何在终端直接交互。

**Comment by yanyongyu** [comment]
直接点击或者建盘输入，如果无法交互请更换终端

**Comment by Agnes4m** [comment]
## win(没办法输入)
![image](https://github.com/nonebot/adapter-console/assets/70925546/bab9e7e7-c1ac-4055-8959-9fc58dce3210)
## linux(输入无反应)
![image](https://github.com/nonebot/adapter-console/assets/70925546/5d2d0adc-b1f2-4993-8d4b-e330f35674bb)

**Comment by yanyongyu** [comment]
你确定你加载了console适配器吗，这看上去就是完全没有加载。

**Comment by Agnes4m** [comment]
找到问题了，由于我生成了bot.py文件，他并不能直接通过nb安装console适配器，而是需要再手动添加
